config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => 'admin/sidekiq'

  get 'search', controller: "search"
  post 'search/results', controller: "search"
  get 'search/external', controller: "search"
  get 'api/definitions', controller: "api"
  get 'api/add_user_word', controller: "api"
  get 'notes/external', controller: "notes"

  root 'categories#index'

  resources :words do 
    member do
      put 'add'
    end
  end

  resources :word_scores

  resources :user_words do 
    member do
      put 'remove'
    end
  end

  resources :categories do
    post 'find_words', :on => :collection
    post 'update_range', :on => :collection
    post 'update_range', :on => :collection
    post 'create_levels'
    post :create_wrong_words_level
    resources :levels
  end

  resources :category_words do
    post 'disable'
    post 'enable'
  end

  resources :user_level_categories, controller: 'level_categories', type: 'UserCategory' 

  resources :level_instances do
    resources :run, controller: 'level_instances/run'

    get 'finished', to: 'level_instances#finished'

    post 'select_masculine', to: 'level_instances#select_masculine'
    post 'select_feminine', to: 'level_instances#select_feminine'

  end

  resources :users do
    resource :user_configuration do
      post 'enable_microphone', to: 'user_configurations#enable_microphone'
      post 'disable_microphone', to: 'user_configurations#disable_microphone'

      post 'enable_sound', to: 'user_configurations#enable_sound'
      post 'disable_sound', to: 'user_configurations#disable_sound'

      post 'enable_speak', to: 'user_configurations#enable_speak'
      post 'disable_speak', to: 'user_configurations#disable_speak'
    end
  end

end

app/models/level_instance.rb
class LevelInstance < ActiveRecord::Base
  belongs_to :level
  belongs_to :user

  has_many :word_scores, -> { order 'created_at asc' }
end

app/controllers/level_instances/run_controller.rb
class LevelInstances::RunController < ApplicationController
  include Wicked::Wizard

  before_action :authenticate_user!
  respond_to :html, :js

  steps :show_word, :check_word, :finish

  def show
    @level_instance = LevelInstance.find(params[:level_instance_id])

    @speak = UserConfiguration.where({:user => current_user}).first[:speak]
    ap @speak

    case step
    when :start
      if @level_instance.level

        @name = @level_instance.level[:name]
        @description = @level_instance.level[:description]

        @word_correct_counts = {}

        @level_instance.word_scores.each do |level_word_score|
          correct_count = 0

          word_scores_for_word = current_user.word_scores.where(word: level_word_score.word)

          word_scores_for_word.each do |word_word_score|
            if word_word_score[:correct]
              correct_count += 1
            end
            
            if word_word_score[:correct] != nil
              @word_correct_counts[level_word_score.word] = correct_count / word_scores_for_word.count.to_f
            else
              @word_correct_counts[level_word_score.word] = "-"
            end
          end
        end
      end

    when :show_word
      set_definition @level_instance

    when :check_word
      set_definition @level_instance

      @correct = @word_score[:correct]
      @f_clicked = false
      @word_gender = @word_score.word[:gender]

      if @correct
        if @word_gender == "f"
          @f_clicked = true
        end
      else 
        if @word_gender == "m"
          @f_clicked = true
        end
      end

    when :finish
    end

    render_wizard 
  end

  def update
    @level_instance = LevelInstance.find(params[:level_instance_id])

    case step
    when :start
    when :show_word

      word_score = @level_instance.word_scores[@level_instance[:complete_count]]
      word = word_score.word

      # Check which button was pressed and if it was correct
      correct = true

      if word[:gender] == "f"
        if params[:F]
          correct = true
        else
          correct = false
        end
      else
        if params[:M]
          correct = true
        else
          correct = false
        end
      end

      #  Save the level correct completion score
      if correct
        @level_instance.correct_completion_percent = @level_instance.correct_completion_percent + 1.0/@level_instance.word_scores.count * 100
        @level_instance.save!
      end

      # Make a new word's score
      word_score.update_attribute(:correct,  correct)
      ap "showowrdupdate"
      ap word_score

    when :check_word
      @level_instance.complete_count = @level_instance.complete_count + 1

      if @level_instance.complete_count < @level_instance.word_scores.count
        jump_to(:show_word)
      end

    end

    # @level_instance.save!

    render_wizard @level_instance

  end

  def create
  end

private 

  def set_definition level_instance
    ap level_instance.word_scores
    @word_score = level_instance.word_scores[level_instance[:complete_count]]

    word = @word_score.word

    @definition_fr = word[:definition_fr]
    if @definition_fr == nil
      @definition_fr = "-"
    end

    @definition_en = word[:definition_en]
    if @definition_en == nil
      @definition_en = "-"
    else
      @definition_en = "("+@definition_en.uniq.join(", ")+")"
    end
  end
end

app/controllers/level_instances_controller.rb
class LevelInstancesController < ApplicationController
  respond_to :html, :js

  # GET /level_instances
  def index
  end


  # POST /level_instances/create
  def create
    level = Level.find(params[:level_id])

    @level_instance = LevelInstance.new({:level => level, :user => current_user, :complete_count => 0, :correct_completion_percent => 0})

    @words = []
    level.level_words.sort_by(&:updated_at).each do |lw|
      @words.push(lw.word)
    end

    @words.each do |word|
      cat = @level_instance.level.category
      WordScore.create({:level_instance => @level_instance, :word => word, :category => cat, :user => current_user})
    end

    redirect_to action: "show", id: @level_instance

    # redirect_to level_instance_run_index_path(:level_instance_id => @level_instance.id)
  end

  def show
    @level_instance = LevelInstance.find(params[:id])
    @speak = UserConfiguration.where({:user => current_user}).first[:speak]
    set_definition @level_instance
  end

  def finished
    @level_instance = LevelInstance.find(params[:level_instance_id])
  end

  def select_masculine
    check_word params[:level_instance_id], "m"
  end

  def select_feminine
    check_word params[:level_instance_id], "f"
  end
  
private 

  def set_definition level_instance
    @word_score = level_instance.word_scores[level_instance[:complete_count]]

    w = @word_score.word
    @word = w[:word]

    @definition_fr = w[:definition_fr]
    if @definition_fr == nil
      @definition_fr = "-"
    end

    @definition_en = w[:definition_en]
    if @definition_en == nil
      @definition_en = "-"
    else
      @definition_en = "("+@definition_en.uniq.join(", ")+")"
    end
  end

  def check_word level_instance_id, gender
    @level_instance = LevelInstance.find(level_instance_id)
    word_score = @level_instance.word_scores[@level_instance[:complete_count]]
    @correct = false
    @wait_time = 1500
    if word_score.word[:gender] == gender
      @correct = true
      @wait_time = 300
    end
    word_score.update_attributes({:correct => @correct, :seen => true})

    @level_instance.update_attribute(:complete_count,  @level_instance[:complete_count] + 1)
    
    if @level_instance[:complete_count] >= @level_instance.word_scores.count
       #  DO SOMETHING
    else
      set_definition @level_instance
    end

    @speak = UserConfiguration.where({:user => current_user}).first[:speak]

    respond_to do |format|
      format.js
    end
end

end

app/views/level_instances/run/check_word.html.erb
<div class="jumbotron" id="check_word"> 
<div class="container">

      <div align="right">
      <% if @play_word_sound %>
        <button class="btn btn-default" type="button"> <span class="glyphicon glyphicon-volume-off fa-1x" /></button>
      <% else %>
          <button class="btn btn-default" type="button"> <span class="glyphicon glyphicon-volume-up" /></button>
      <% end %> 
      </div>

    <h1 align="center" id="word"><%= @word_score.word[:word] %></h1>
    <p align="center" class="word-def-fr"><%= @definition_fr %> </p>
    <p align="center" class="word-def-en"><%= @definition_en %> </p>

    <div align="center">

    <% if @f_clicked %>
      <% if @correct %>
        <button class="btn btn-lg btn-success" type="button"> F <span class="glyphicon glyphicon-ok" /></button>
      <% else %>
        <button class="btn btn-lg btn-danger" type="button"> F <span class="glyphicon glyphicon-remove" /></button>
      <% end %>
      <button class="btn btn-lg" type="button">M</button>
    <% else %>
      <button class="btn btn-lg" type="button">F</button>
      <% if @correct %>
        <button class="btn btn-lg btn-success" type="button">M<span class="glyphicon glyphicon-ok" /></button>
      <% else %>
        <button class="btn btn-lg btn-danger" type="button">M<span class="glyphicon glyphicon-remove" /></button>
      <% end %>
    <% end %>
    </div>

    <%= form_for @level_instance, url: wizard_path, method: :put do |f| %>
      <div class="row">
        <div class="col-sm-12 text-center"'>
          <input type="submit" value="Next" id="next" class="btn btn-primary btn-lg hidden">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/level_instances/run/check_word.js.erb
setTimeout(function(){ $("#next").click(); }, 5000);

app/views/level_instances/run/finish.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
       <h1> Finished </h1>
        <%= link_to "Finish", category_path(@level_instance.level.category), :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/level_instances/run/show_word.html.erb
<div class="jumbotron" id="show_word"> 
  <div class="container">
      <div align="right">

        <!-- DISABLE SPEAK -->
        <% if @speak %>
        <div id="disable-speak">
        <% else %>
        <div id="disable-speak" style="display: none;">
        <% end %>
          <%= link_to disable_speak_user_user_configuration_path(current_user.user_configuration), method: :post, class: "btn btn-default", remote: true do %>
            <span class="glyphicon glyphicon-volume-up fa-1x" />
          <% end %>
        </div>

        <!-- ENABLE SPEAK -->
        <% if @speak %>
        <div id="enable-speak" style="display: none;">
        <% else %>
        <div id="enable-speak">
        <% end %>
        
          <%= link_to enable_speak_user_user_configuration_path(current_user.user_configuration), method: :post, class: "btn btn-default", remote: true do %>
            <span class="glyphicon glyphicon-volume-off fa-1x" />
          <% end %>
        </div>
      </div>

    <% if @speak %>
    <h1 align="center" id="word-speak"><%= @word_score.word[:word] %></h1>
    <% else %>
    <h1 align="center" id="word-mute"><%= @word_score.word[:word] %></h1>
    <% end %>
    <p align="center" class="word-def-fr"><%= @definition_fr %> </p>
    <p align="center" class="word-def-en"><%= @definition_en %> </p>

    <%= form_for @level_instance, url: wizard_path(:show_word), method: :put do |f| %>
      <div class="row">
        <div class="col-sm-12 text-center"'>
          <input name="word_id" type="hidden" value="<%= @word_id %>" />

          <input type="submit" id="feminin" value="F" class="btn btn-primary btn-lg" name="F">
          <input type="submit" id="masculin" value="M" class="btn btn-primary btn-lg" name="M">
      </div>
    </div>
  <% end %>
</div>

app/views/level_instances/run/start.html.erb
<div class="jumbotron">
  <div class="container">


    <div class="row">
      <div class="col-xs-12" >


        <div class="row">
          <h1 class="text-center"><%= @name %></h1>
        </div>

        <div class="row">

          <div class="col-xs-4 text-center">
            <%= link_to level_instances_path(:level_id => @level_instance.level.id-1), :method => :post, :class => "btn btn-lg" do %>
              <button class="btn btn-primary btn-lg " type="button"> <span class="glyphicon glyphicon-chevron-left fa-1x" /></button>
            <% end %>
          </div>
          
          <div class="col-xs-4">
              <p class="text-center"><%= @description %> </p>
          </div>

          <div class="col-xs-4 text-center">
            <%= link_to level_instances_path(:level_id => @level_instance.level.id+1), :method => :post, :class => "btn btn-lg" do %>
              <button class="btn btn-primary btn-lg " type="button"> <span class="glyphicon glyphicon-chevron-right fa-1x" /></button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-sm-12 text-center"'>
          <%= form_for @level_instance, url: wizard_path(:start), method: :put do |f| %>
              <%= button_tag(type: 'submit', class: "btn btn-primary btn-lg") do %>
                Start
                <span class="glyphicon glyphicon-play"></span> 
              <% end %>
          <% end %>
      </div>
    </div>


    <br>
    <br>
    <br>

    <div class="row">
      <div class="col-xs-3 col-xs-offset-4"'>
        <table class="table">
          <thead>
            <tr>
            <th width="40%">Word</th>
            <th width="20%">Gender</th>
            <th width="20%"><span data-toggle="tooltip" style="border-bottom: 1px dotted black" title="Over the last three runs.">Correct</span></th>
            </tr>
          </thead>
          <tbody>
            <% @level_instance.word_scores.each do |word_score| %>
              <tr>
                <td align="left">
                <%= word_score.word[:word]%>
                <% if @word_correct_counts[word_score.word] == 1 %>
                  <span class=" glyphicon glyphicon-ok-circle" style='color:green'></span></td>
                <% else %>
                  <span class=" glyphicon glyphicon-remove-circle" style='color:red'></span></td>
                <% end %>
                <td><%= word_score.word[:gender] %></td>

                <% if @word_correct_counts[word_score.word] == "-" %>
                  <td> - </td>
                <% else %>
                  <td><%= (@word_correct_counts[word_score.word] * 100).to_i %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>