config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => 'admin/sidekiq'

  get 'search', controller: "search"
  post 'search/results', controller: "search"
  get 'search/external', controller: "search"
  get 'api/definitions', controller: "api"
  get 'api/add_user_word', controller: "api"
  get 'notes/external', controller: "notes"

  root 'categories#index'

  resources :words do 
    member do
      put 'add'
    end
  end

  resources :word_scores

  resources :user_words do 
    member do
      put 'remove'
    end
  end

  resources :categories do
    post 'find_words', :on => :collection
    post 'update_range', :on => :collection
    post 'update_range', :on => :collection
    post 'create_levels'
    post :create_wrong_words_level
    resources :levels
  end

  resources :category_words do
    post 'disable'
    post 'enable'
  end

  resources :user_level_categories, controller: 'level_categories', type: 'UserCategory' 

  resources :level_instances do
    resources :run, controller: 'level_instances/run'

    get 'finished', to: 'level_instances#finished'

    post 'select_masculine', to: 'level_instances#select_masculine'
    post 'select_feminine', to: 'level_instances#select_feminine'

  end

  resources :users do
    resource :user_configuration do
      post 'enable_microphone', to: 'user_configurations#enable_microphone'
      post 'disable_microphone', to: 'user_configurations#disable_microphone'

      post 'enable_sound', to: 'user_configurations#enable_sound'
      post 'disable_sound', to: 'user_configurations#disable_sound'

      post 'enable_speak', to: 'user_configurations#enable_speak'
      post 'disable_speak', to: 'user_configurations#disable_speak'
    end
  end

end

app/models/level.rb
class Level < ActiveRecord::Base

  belongs_to :category

  has_many  :level_words
  has_many  :words, through: :level_words
  
  has_many  :level_instances
  
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :authenticate_user!

  def index
    @levels = Level.all

    @level_completion = {}

    @levels.each do |level|
      highest_level_completion = 0
      LevelInstance.where(:level_id => level.id).each do |level_instance|
        if level_instance[:correct_completion_percent] > highest_level_completion
          highest_level_completion = level_instance[:correct_completion_percent]
        end
      end
      @level_completion[level.id] = highest_level_completion
    end
  end


  def show
    @level = Level.find(params[:id])

    @words = []
    @level.level_words.sort_by(&:updated_at).each do |lw|
      @words.push(lw.word)
    end

    @name = @level[:name]
    @description = @level[:description]

    @word_correct_counts = {}

    @level.words.each do |word|
      @word_correct_counts[word] = "-"
    end
    #   correct_count = 0

    #   word_scores_for_word = current_user.word_scores.where(word: level_word_score.word)

    #   word_scores_for_word.each do |word_word_score|
    #     if word_word_score[:correct]
    #       correct_count += 1
    #     end
        
    #     if word_word_score[:correct] != nil
    #       @word_correct_counts[level_word_score.word] = correct_count / word_scores_for_word.count.to_f
    #     else
    #       @word_correct_counts[level_word_score.word] = "-"
    #     end
    #   end
    # end
  end

  def get_level_completion level_id
    LevelInstance.where({:level_id => level_id})
  end

end

app/helpers/level_helper.rb
module LevelHelper
end

app/views/levels/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <h1 align="center">Levels</h1>
      </div>

      <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
      <%= link_to create_wrong_words_level_level_instances_path, :method => :post, :class => "btn btn-lg", :title => "Words you got wrong." do %>
        <%= image_tag("answer_wrong.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
        <span class="level_title"><%= "Hard Words" %></span>
      <% end %>
      </div>
      </div>

      <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
      <% @levels.each do |level| %>
        <%= link_to level_path(level.id), :class => "btn btn-lg", :title => Level.find(level.id)[:description] do %>
          <% if @level_completion[level.id] >= 100 %>
            <%= image_tag("complete-100.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% elsif @level_completion[level.id] > 75 %>
            <%= image_tag("complete-75.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% elsif @level_completion[level.id] > 25 %>
            <%= image_tag("complete-50.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% elsif @level_completion[level.id] > 0 %>
            <%= image_tag("complete-25.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% else %>
            <%= image_tag("complete-0.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% end %>
          <span class="level_title"><%= Level.find(level.id)[:name] %></span>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/levels/show.html.erb
<div class="jumbotron">
  <div class="container">


    <div class="row">
      <div class="col-xs-12" >


        <div class="row">
          <h1 class="text-center"><%= @name %></h1>
        </div>

        <div class="row">

          <div class="col-xs-4 text-center">
            <%= link_to category_level_path(@level.category.id, @level.id-1), :class => "btn btn-lg" do %>
              <button class="btn btn-primary btn-lg " type="button"> <span class="glyphicon glyphicon-chevron-left fa-1x" /></button>
            <% end %>
          </div>
          
          <div class="col-xs-4">
              <p class="text-center"><%= @description %> </p>
          </div>

          <div class="col-xs-4 text-center">
            <%= link_to category_level_path(@level.category.id, @level.id+1), :class => "btn btn-lg" do %>
              <button class="btn btn-primary btn-lg " type="button"> <span class="glyphicon glyphicon-chevron-right fa-1x" /></button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-sm-12 text-center"'>
        <%= link_to level_instances_path(:level_id => @level.id), :method => :post, :class => "btn btn-lg btn-primary", :title => Level.find(@level.id)[:description] do %>
            Start
            <span class="glyphicon glyphicon-play"></span> 
        <% end %>
      </div>
    </div>


    <br>
    <br>
    <br>

    <div class="row">
      <div class="col-xs-3 col-xs-offset-4"'>
        <table class="table">
          <thead>
            <tr>
            <th width="40%">Word</th>
            <th width="20%">Gender</th>
            <th width="20%"><span data-toggle="tooltip" style="border-bottom: 1px dotted black" title="Over the last three runs.">Correct</span></th>
            </tr>
          </thead>
          <tbody>
            <% #@level.words.order("frequency DESC").each do |word| %>
            <% @words.each do |word| %>
              <tr>
                <td align="left">
                <%= word[:word]%>
                <% if @word_correct_counts[word] == 1 %>
                  <span class=" glyphicon glyphicon-ok-circle" style='color:green'></span></td>
                <% else %>
                  <span class=" glyphicon glyphicon-remove-circle" style='color:red'></span></td>
                <% end %>
                <td><%= word[:gender] %></td>

                <% if @word_correct_counts[word] == "-" %>
                  <td> - </td>
                <% else %>
                  <td><%= (@word_correct_counts[word] * 100).to_i %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>