config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => 'admin/sidekiq'

  get 'search', controller: "search"
  post 'search/results', controller: "search"
  get 'search/external', controller: "search"
  get 'api/definitions', controller: "api"
  get 'api/add_user_word', controller: "api"
  get 'notes/external', controller: "notes"

  root 'categories#index'

  resources :words do 
    member do
      put 'add'
    end
  end

  resources :word_scores

  resources :user_words do 
    member do
      put 'remove'
    end
  end

  resources :categories do
    post 'find_words', :on => :collection
    post 'update_range', :on => :collection
    post 'update_range', :on => :collection
    post 'create_levels'
    post :create_wrong_words_level
    resources :levels
  end

  resources :category_words do
    post 'disable'
    post 'enable'
  end

  resources :user_level_categories, controller: 'level_categories', type: 'UserCategory' 

  resources :level_instances do
    resources :run, controller: 'level_instances/run'

    get 'finished', to: 'level_instances#finished'

    post 'select_masculine', to: 'level_instances#select_masculine'
    post 'select_feminine', to: 'level_instances#select_feminine'

  end

  resources :users do
    resource :user_configuration do
      post 'enable_microphone', to: 'user_configurations#enable_microphone'
      post 'disable_microphone', to: 'user_configurations#disable_microphone'

      post 'enable_sound', to: 'user_configurations#enable_sound'
      post 'disable_sound', to: 'user_configurations#disable_sound'

      post 'enable_speak', to: 'user_configurations#enable_speak'
      post 'disable_speak', to: 'user_configurations#disable_speak'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :levels
  has_many :category_words
  has_many :word_scores
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @levels = @category.levels
    @levels = @levels.sort_by(&:updated_at)

    # @words = []
    # @level.level_words.sort_by(&:updated_at).each do |lw|
    #   @words.push(lw.word)
    # end

    @level_completion = {}

    @levels.each do |level|
      highest_level_completion = 0
      LevelInstance.where(:level_id => level.id).each do |level_instance|
        if level_instance[:correct_completion_percent] > highest_level_completion
          highest_level_completion = level_instance[:correct_completion_percent]
        end
      end
      @level_completion[level.id] = highest_level_completion
    end
  end

  def destroy
    ap params
    @category = Category.find(params[:id])
    destroy_existing_levels(@category)
    ap @category.category_words  
    @category.category_words.destroy_all
    @category.destroy
    redirect_to categories_path
  end

  def update
    if category_params
      @category = Category.find(params[:id])
      @category.update_attributes!(category_params)
    else
      cat_word = CategoryWord.find(params[:cat_word_id])
      cat_word.update_attributes({:include_word => !cat_word[:include_word]})
    end

    redirect_to edit_category_path({:id=>params[:id]})
  end

  def edit
    @category = Category.find(params[:id])

    @selected_words = []
    @removed_words = []
  
    @category.category_words.each do |w|
      if w.word[:frequency_lemma] != nil
        if w.include_word
          @selected_words.push(w)
        else
          @removed_words.push(w)
        end
      else
        @selected_words.push(w)
      end
    end

    if params[:sort] == "frequency"
      @selected_words = @selected_words.sort_by { |k| k.word[:frequency_lemma] }
      @removed_words = @removed_words.sort_by { |k| k.word[:frequency_lemma] }
    else
      @selected_words = @selected_words.sort_by { |k| k[params[:sort]] }
      @removed_words = @removed_words.sort_by { |k| k[params[:sort]] }
    end


    if params[:direction] == "desc"
      @selected_words = @selected_words.reverse!
      @removed_words = @removed_words.reverse!
    end

  end

  def new
    @category = Category.new

    @selected_words = []
    @removed_words = []
  end

  def find_words

    ap "find_words"
    ap params

    if params[:category][:id] != nil and params[:category][:id] != ""
      category = Category.find(params[:category][:id])
      category.update(category_params)
    else
      category = Category.create(category_params.merge({:word_frequency_maximum => 1000000}))
    end


    category.category_words.each do |cat_word|
      cat_word.destroy
    end

    HardWorker.perform_async(category.id)
    redirect_to edit_category_path({:id=>category.id})
  end

  def update_range
    category = Category.find(params[:category][:id])
    word_frequency_maximum = category_params[:word_frequency_maximum].to_i
    category.update_attribute(:word_frequency_maximum, word_frequency_maximum)
    category.save!
    Processing::WordSourceCounter.select_included_words(category)
    redirect_to edit_category_path({:id=>params[:category][:id]})
  end

  def create_levels
    redirect_to categories_path

    @category = Category.find(params[:category_id])

    destroy_existing_levels(@category)

    @selected_words = []
  
    @category.category_words.each do |w|
      if w.include_word
        @selected_words.push(w)
      end
    end

    @selected_words = @selected_words.sort_by &:url_frequency
    @selected_words = @selected_words.reverse!

    @level_size = @selected_words.count
    if @selected_words.count > 200
      @level_size = 50
    end

    counter =0
    l = nil

    # ap @selected_words

    @selected_words.each do |wc|
      w = wc.word
      if counter % @level_size == 0
        l = Level.create({:name=>"Level #{counter/@level_size + 1}", :description => "Words you'll see.", :category => wc.category})
      end
      LevelWord.create({:level => l, :word => w})
      counter = counter + 1
    end
  end

  def create_wrong_words_level
      category = Category.find(params[:category_id])
      word_scores = WordScore.where({:user_id=>current_user, :category => category})

      wrong_words = []
      word_scores.each do |ws|
        if ws.correct == false
          wrong_words.push(ws.word)
        end
      end


      l = Level.create({:name=>"Wrong words: #{category[:name]}", :description => "Words you got wrong.", :category => category})

      wrong_words.uniq.each do |w|
        LevelWord.create({:level => l, :word => w})
      end

      redirect_to category_level_path(category, l)

      # @level_instance = LevelInstance.create({:user => current_user, :category => category, :complete_count => 0, :correct_completion_percent => 0, :word_scores => wrong_words})
      # success = @level_instance.save
      # redirect_to level_instance_run_index_path(:level_instance_id => @level_instance.id)
  end

  private

  def destroy_existing_levels category
    Level.where({:category => category}).each do |level|
      level.level_words.destroy_all

      level.level_instances.each do |li|
        li.word_scores.destroy_all
      end

      level.level_instances.destroy_all
    end

    Level.destroy_all({:category => category})
  end

  def category_params
    if params[:category]
      params.require(:category).permit(:word_sources, :name, :word_frequency_maximum, :word_score_maximum)
    else 
      false
    end
  end
  
  def sort_column
    if CategoryWord.column_names.include?(params[:sort]) or Word.column_names.include?(params[:sort])
      params[:sort]
    else
      "name"
    end
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
      <%= form_for @category, :url => { :action => "find_words" }, method: "push" do |f| %>
        <div>Name: <%= f.text_field :name %></div>
        <div>Link Sources:</div><div><%= f.text_area(:word_sources, size: "24x6") %></div>
        <%= f.hidden_field :id, :value => @category[:id]%>
        <div><%= f.submit "Scan Sources",  :class => "btn btn-primary"%></div>
      <% end %>

        <br />
    <br />

    <% if @category[:word_sources] != nil and @category[:word_sources] != "" %>
      <%= form_for @category, :url => { :action => "update_range" }, method: "push" do |f| %>
        <%= f.hidden_field :id, :value => @category[:id]%>
        <%= f.label :word_frequency_maximum %>  
        <%= f.text_field(:word_frequency_maximum) %>
        <br />
        <%= f.label :word_score_maximum %>  
        <%= f.text_field(:word_score_maximum) %>
        <div><%= f.submit "Update Ranges",  :class => "btn btn-primary"%></div>
      <% end %>
      </div>
    </div>
  
    <% if @category.id %>
      <%= link_to "Create Levels", category_create_levels_path(@category), :method => :post, :class => "btn btn-primary" %>
    <% end %>

  <div class="row">
    <div class="col-xs-12"'>
      <div class="edit_category_words" id="selected_words">
        <h3>Selected Words (<%= @selected_words.count %>)</h3>
        <table class="table">
          <thead>
            <tr>
            <th width="20%">Word</th>
            <th width="10%">Gender</th>
            <th width="15%"><%= sortable("category_ranking", "Rank Score") %></th>
            <th width="15%"><%= sortable("url_frequency", "Source Frequency") %></th>
            <th width="15%"><%= sortable("frequency", "General Frequency") %></th>
            </tr>
          </thead>
          <tbody>
            <% @selected_words.each do |cat_word| %>
              <tr> 
              <td> <%= link_to category_word_disable_path(cat_word), :method => :post do %>
                      <span class="glyphicon glyphicon-remove" style='color:grey' />
                  <% end %> <%= link_to cat_word.word[:word], word_path(cat_word.word) %> </td>
              <td> <%= cat_word.word[:gender] %> </td>
              <td> <%= number_with_delimiter(cat_word[:category_ranking].to_i) %> </td>
              <td> <%= number_with_delimiter(cat_word[:url_frequency]) %> </td>
              <td> <%= number_with_delimiter(cat_word.word[:frequency_lemma]) %> </td>
              <td> BLASG </td>
              <td>  
              </td>
             </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12"'>
      <div class="edit_category_words" id="removed_words">
        <h3>Removed Words (<%= @removed_words.count %>)</h3>
        <table class="table">
          <thead>
            <tr>
            <th width="20%">Word</th>
            <th width="10%">Gender</th>
            <th width="15%"><%= sortable("category_ranking", "Rank Score") %></th>
            <th width="15%"><%= sortable("url_frequency", "Source Frequency") %></th>
            <th width="15%"><%= sortable("frequency", "General Frequency") %></th>
            </tr>
          </thead>
          <tbody>
            <% @removed_words.each do |cat_word| %>
              <tr> 
              <td> <%= link_to category_word_enable_path(cat_word), :method => :post do %>
                      <span class="glyphicon glyphicon-plus" style='color:grey' />
                  <% end %> <%= link_to cat_word.word[:word], word_path(cat_word.word) %> </td>
              <td> <%= cat_word.word[:gender] %> </td>
              <td> <%= number_with_delimiter(cat_word[:category_ranking].to_i) %> </td>
              <td> <%= number_with_delimiter(cat_word[:url_frequency]) %> </td>
              <td> <%= number_with_delimiter(cat_word.word[:frequency_lemma]) %> </td>
              <td>  
              </td>
             </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <% end %>

  </div>
</div>

app/views/categories/edit.html.erb
<%= render "form" %>

app/views/categories/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <h1 align="center">Level Categories</h1>
      </div>

      <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
      <%= link_to new_category_path, :class => "btn btn-lg", :title => "Add" do %>
            <%= image_tag("complete-100.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <span class="level_title">+</span>
      <% end %>

      <% @categories.each do |category| %>
        <%= link_to category_path(category.id), :class => "btn btn-lg", :title => category[:description] do %>
            <%= image_tag("complete-100.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <span class="level_title"><%= category[:name] %></span>
        <% end %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "form" %>

app/views/categories/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <h1 align="center"><%= @category.name %> </h1>
      </div>

     <%= link_to edit_category_path(@category), class: "btn btn-default", method: :get do %>
        <span class=" glyphicon glyphicon-edit" />
      <% end %>
     <%= link_to category_path(@category), class: "btn btn-default", method: :delete do %>
        <span class=" glyphicon glyphicon-remove" />
      <% end %>
        

      <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
      <%= link_to category_create_wrong_words_level_path(@category), :method => :post, :class => "btn btn-lg", :title => "Words you got wrong." do %>
        <%= image_tag("answer_wrong.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
        <span class="level_title"><%= "Hard Words" %></span>
      <% end %>
      </div>
      </div>

      <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
      <% @levels.each do |level| %>
        <%= link_to category_level_path(level.category, level), :class => "btn btn-lg", :title => Level.find(level.id)[:description] do %>
          <% if @level_completion[level.id] >= 100 %>
            <%= image_tag("complete-100.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% elsif @level_completion[level.id] > 75 %>
            <%= image_tag("complete-75.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% elsif @level_completion[level.id] > 25 %>
            <%= image_tag("complete-50.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% elsif @level_completion[level.id] > 0 %>
            <%= image_tag("complete-25.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% else %>
            <%= image_tag("complete-0.png", :border => 0, :alt => '', :title => '', :size => "80x80", :class=>"img-responsive") %>
          <% end %>
          <span class="level_title"><%= Level.find(level.id)[:name] %></span>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>